[versions]

kotlin = "1.9.25"
spring-boot = "3.5.7"
spring-dependency-management = "1.1.7"
mockk = "1.14.2"
springmockk = "3.0.1"
epage-restdocs = "0.19.4"
gson = "2.13.0"
jjwt = "0.12.3"

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
epage-restdocs = { id = "com.epages.restdocs-api-spec", version.ref = "epage-restdocs" }

[libraries]

# mockk
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }

# restdocs
epage-restdocs-mockmvc = { module = "com.epages:restdocs-api-spec-mockmvc", version.ref = "epage-restdocs" }

# gson
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# jjwt
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }